name: GUItest
version: '1-0'
main: com.github.ytshiyugh.guitest.GUItest
api-version: 1.18
authors: [ ytshiyugh ]
description: Plugin for gui test.
commands:
  gui:
    description: gui inventory open test.
  newpstd:
    description: new deposit
  newpsts:
    description: new show
